# Maven Wrapper properties
# This lets you build the project without a pre-installed Maven (it will be downloaded automatically).
#
# Maven distribution to use:
distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.9.9/apache-maven-3.9.9-bin.zip
# Wrapper JAR location to download (Takari Maven Wrapper):
wrapperUrl=https://repo.maven.apache.org/maven2/org/apache/maven/wrapper/maven-wrapper/3.3.2/maven-wrapper-3.3.2.jar

